import { RULE_LABELS, type Report, type Severity } from "../types.js";

const ICON: Record<Severity, string> = { error: "🔴", warning: "🟡", info: "🔵" };

/** Render a report as a shareable Markdown document. */
export function toMarkdown(report: Report): string {
  const lines: string[] = [];
  const s = report.summary;
  lines.push("# licenselint report", "");
  lines.push(
    `**Overall: ${s.score}/100 (${s.grade})** · ${s.dependencies} dependencies · ` +
      `${s.errors} error(s), ${s.warnings} warning(s), ${s.infos} info`,
    "",
  );
  lines.push(`> Generated by ${report.tool} v${report.version} on ${report.generatedAt}`, "");

  // License class breakdown.
  lines.push("## License breakdown", "");
  lines.push("| Class | Count |", "| --- | --- |");
  for (const b of s.byClass) lines.push(`| ${b.label} | ${b.count} |`);
  lines.push("");

  // Top licenses.
  lines.push("## Licenses in use", "");
  lines.push("| License | Packages |", "| --- | --- |");
  for (const l of s.licenses.slice(0, 30)) lines.push(`| \`${l.id}\` | ${l.count} |`);
  lines.push("");

  // Issues.
  if (report.issues.length === 0) {
    lines.push("## Issues", "", "✅ No license policy issues found.", "");
  } else {
    lines.push("## Issues", "");
    const byRule = new Map<string, typeof report.issues>();
    for (const issue of report.issues) {
      const arr = byRule.get(issue.rule) ?? [];
      arr.push(issue);
      byRule.set(issue.rule, arr);
    }
    for (const [rule, issues] of byRule) {
      lines.push(`### ${RULE_LABELS[rule as keyof typeof RULE_LABELS] ?? rule} (${issues.length})`);
      for (const i of issues) {
        lines.push(`- ${ICON[i.severity]} **${i.dependency}@${i.version}** — ${i.message}`);
        if (i.fix) lines.push(`  - 💡 ${i.fix}`);
      }
      lines.push("");
    }
  }
  return lines.join("\n");
}
